# Generated by Django 3.0.2 on 2020-05-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioDataModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(choices=[('< 60inches(152.40cm)', '< 60inches(152.40cm)'), ('> 60inches(152.40cm) but < 65inches(165.10cm)', '> 60inches(152.40cm) but < 65inches(165.10cm)'), ('> 65inches(165.10cm) but < 70inches(177.80cm)', '> 65inches(165.10cm) but < 70inches(177.80cm)'), ('> 70inches(177.80) but < 75inches(190.50cm)', '> 70inches(177.80) but < 75inches(190.50cm)'), ('> 75inches(190.50cm) but < 80inches(203.20cm)', '> 75inches(190.50cm) but < 80inches(203.20cm)'), ('> 80inches(203.20cm) but < 85inches(215.90cm)', '> 80inches(203.20cm) but < 85inches(215.90cm)'), ('> 85inches(215.90cm) but < 90inches(228.6)', '> 85inches(215.90cm) but < 90inches(228.6)'), ('> 60inches(152.40cm)', '> 60inches(152.40cm)')], max_length=100)),
                ('eye_color', models.CharField(choices=[('light', 'light'), ('brown', 'brown'), ('black', 'black')], max_length=100)),
                ('hair_color', models.CharField(choices=[('light', 'light'), ('brown', 'brown'), ('black', 'black')], max_length=100)),
                ('complexion', models.CharField(choices=[('very light', 'very light'), ('light', 'light'), ('brown/chocolate', 'brown/chocolate'), ('dark brown', 'dark brown'), ('very dark', 'very dark')], max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('religion', models.CharField(choices=[('christainity', 'christainity'), ('islam', 'islam'), ('traditional', 'traditional'), ('atheist', 'atheist')], max_length=100)),
                ('describe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserMoreInfoModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(choices=[('Reading', 'Reading'), ('Watching TV', 'Watching TV'), ('Family Time', 'Family Time'), ('Going to Movies', 'Going to Movies'), ('Fishing', 'Fishing'), ('Computer', 'Computer'), ('Gardening', 'Gardening'), ('Walking', 'Walking'), ('Exercise', 'Exercise'), ('Listening to Music', 'Listening to Music'), ('Entertaining', 'Entertaining'), ('Hunting', 'Hunting'), ('Team Sports', 'Team Sports'), ('Shopping', 'Shopping'), ('Traveling', 'Traveling'), ('Sleeping', 'Sleeping'), ('Socializing', 'Socializing'), ('Sewing', 'Sewing'), ('Church Activities', 'Church Activities'), ('Relaxing', 'Relaxing'), ('Playing Music', 'Playing Music'), ('Housework', 'Housework'), ('Crafts', 'Crafts'), ('Watching Sports', 'Watching Sports'), ('Bicycling', 'Bicycling'), ('Playing Cards', 'Playing Cards'), ('Cooking', 'Cooking'), ('Swimming', 'Swimming'), ('Camping', 'Camping'), ('Writing', 'Writing'), ('Animal Care', 'Animal Care'), ('Painting', 'Painting'), ('Running', 'Running'), ('Dancing', 'Dancing'), ('Tennis', 'Tennis'), ('Theater', 'Theater'), ('Beach', 'Beach'), ('Volunteer Work', 'Volunteer Work')], max_length=100)),
                ('do_you_take_alcohol', models.CharField(choices=[('once a year', 'once a year'), ('once a month', 'once a month'), ('once a week', 'once a week'), ('daily', 'daily')], max_length=100)),
                ('do_you_smoke', models.CharField(choices=[('once a year', 'once a year'), ('once a month', 'once a month'), ('once a week', 'once a week'), ('daily', 'daily')], max_length=100)),
                ('sport', models.CharField(choices=[('volleyball', 'volleyball'), ('badminton', 'badminton'), ('running', 'running'), ('basketball', 'basketball'), ('gymnastics', 'gymnastics'), ('table tennis', 'table tennis'), ('handball', 'handball'), ('football', 'football'), ('martial arts', 'martial arts'), ('squash', 'squash'), ('other', 'other')], max_length=100)),
                ('music', models.CharField(choices=[('rap', 'rap'), ('gospel', 'gospel'), ('jazz', 'jazz'), ('blues/soul', 'blues/soul'), ('hip-hop', 'hip-hop'), ('oldies', 'oldies'), ('classical', 'classical'), ('R&B', 'R&B'), ('reggae', 'reggae'), ('others', 'others')], max_length=100)),
            ],
        ),
    ]
