# Generated by Django 3.0.2 on 2020-05-03 11:30

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_biodatamodel2_usermoreinfomodel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BioDataModel2',
        ),
        migrations.DeleteModel(
            name='UserMoreInfoModel2',
        ),
        migrations.RemoveField(
            model_name='biodatamodel',
            name='age',
        ),
        migrations.AlterField(
            model_name='biodatamodel',
            name='complexion',
            field=models.CharField(choices=[('very light', 'very light'), ('light', 'light'), ('brown/chocolate', 'brown/chocolate'), ('dark brown', 'dark brown'), ('very dark', 'very dark')], max_length=100),
        ),
        migrations.AlterField(
            model_name='biodatamodel',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='biodatamodel',
            name='describe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='biodatamodel',
            name='eye_color',
            field=models.CharField(choices=[('light', 'light'), ('brown', 'brown'), ('black', 'black')], max_length=100),
        ),
        migrations.AlterField(
            model_name='biodatamodel',
            name='hair_color',
            field=models.CharField(choices=[('light', 'light'), ('brown', 'brown'), ('black', 'black')], max_length=100),
        ),
        migrations.AlterField(
            model_name='biodatamodel',
            name='height',
            field=models.CharField(choices=[('< 60inches(152.40cm)', '< 60inches(152.40cm)'), ('> 60inches(152.40cm) but < 65inches(165.10cm)', '> 60inches(152.40cm) but < 65inches(165.10cm)'), ('> 65inches(165.10cm) but < 70inches(177.80cm)', '> 65inches(165.10cm) but < 70inches(177.80cm)'), ('> 70inches(177.80) but < 75inches(190.50cm)', '> 70inches(177.80) but < 75inches(190.50cm)'), ('> 75inches(190.50cm) but < 80inches(203.20cm)', '> 75inches(190.50cm) but < 80inches(203.20cm)'), ('> 80inches(203.20cm) but < 85inches(215.90cm)', '> 80inches(203.20cm) but < 85inches(215.90cm)'), ('> 85inches(215.90cm) but < 90inches(228.6)', '> 85inches(215.90cm) but < 90inches(228.6)'), ('> 60inches(152.40cm)', '> 60inches(152.40cm)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='biodatamodel',
            name='religion',
            field=models.CharField(choices=[('christainity', 'christainity'), ('islam', 'islam'), ('traditional', 'traditional'), ('atheist', 'atheist')], max_length=100),
        ),
        migrations.AlterField(
            model_name='biodatamodel',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='do_you_smoke',
            field=models.CharField(choices=[('once a year', 'once a year'), ('once a month', 'once a month'), ('once a week', 'once a week'), ('daily', 'daily')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='do_you_take_alcohol',
            field=models.CharField(choices=[('once a year', 'once a year'), ('once a month', 'once a month'), ('once a week', 'once a week'), ('daily', 'daily')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='hobby',
            field=user.models.ListField(choices=[('Reading', 'Reading'), ('Watching TV', 'Watching TV'), ('Family Time', 'Family Time'), ('Going to Movies', 'Going to Movies'), ('Fishing', 'Fishing'), ('Computer', 'Computer'), ('Gardening', 'Gardening'), ('Walking', 'Walking'), ('Exercise', 'Exercise'), ('Listening to Music', 'Listening to Music'), ('Entertaining', 'Entertaining'), ('Hunting', 'Hunting'), ('Team Sports', 'Team Sports'), ('Shopping', 'Shopping'), ('Traveling', 'Traveling'), ('Sleeping', 'Sleeping'), ('Socializing', 'Socializing'), ('Sewing', 'Sewing'), ('Church Activities', 'Church Activities'), ('Relaxing', 'Relaxing'), ('Playing Music', 'Playing Music'), ('Housework', 'Housework'), ('Crafts', 'Crafts'), ('Watching Sports', 'Watching Sports'), ('Bicycling', 'Bicycling'), ('Playing Cards', 'Playing Cards'), ('Cooking', 'Cooking'), ('Swimming', 'Swimming'), ('Camping', 'Camping'), ('Writing', 'Writing'), ('Animal Care', 'Animal Care'), ('Painting', 'Painting'), ('Running', 'Running'), ('Dancing', 'Dancing'), ('Tennis', 'Tennis'), ('Theater', 'Theater'), ('Beach', 'Beach'), ('Volunteer Work', 'Volunteer Work')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='music',
            field=user.models.ListField(choices=[('rap', 'rap'), ('gospel', 'gospel'), ('jazz', 'jazz'), ('blues/soul', 'blues/soul'), ('hip-hop', 'hip-hop'), ('oldies', 'oldies'), ('classical', 'classical'), ('R&B', 'R&B'), ('reggae', 'reggae'), ('others', 'others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='sport',
            field=user.models.ListField(choices=[('volleyball', 'volleyball'), ('badminton', 'badminton'), ('running', 'running'), ('basketball', 'basketball'), ('gymnastics', 'gymnastics'), ('table tennis', 'table tennis'), ('handball', 'handball'), ('football', 'football'), ('martial arts', 'martial arts'), ('squash', 'squash'), ('other', 'other')], max_length=100),
        ),
    ]
