# Generated by Django 3.0.2 on 2020-05-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200512_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatamodel',
            name='institution',
            field=models.CharField(default='Funaab', max_length=100),
        ),
    ]
