# Generated by Django 3.0.2 on 2020-05-19 01:07

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200518_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='do_you_smoke',
            field=models.CharField(choices=[('Non-smoker', 'Non-smoker'), ('Occasional smoker', 'Occasional smoker'), ('Smoker', 'Smoker')], max_length=200),
        ),
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='do_you_take_alcohol',
            field=models.CharField(choices=[('Non-smoker', 'Non-smoker'), ('Occasional smoker', 'Occasional smoker'), ('Smoker', 'Smoker')], max_length=200),
        ),
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='hobby',
            field=user.models.ListField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='music',
            field=user.models.ListField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='sport',
            field=user.models.ListField(max_length=300),
        ),
    ]
