# Generated by Django 3.0.2 on 2020-05-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200519_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoreinfomodel',
            name='do_you_smoke',
            field=models.CharField(choices=[('Never', 'Never'), ('On special occasion', 'On special occasion'), ('Once a week', 'Once a week'), ('Few times a week', 'Few times a week'), ('Daily', 'Daily')], max_length=200),
        ),
    ]
