# Generated by Django 3.0.2 on 2020-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200519_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatamodel',
            name='height',
            field=models.CharField(choices=[('< 60inches(152.40cm)', '< 60inches(152.40cm)'), ('> 60inches(152.40cm) but < 65inches(165.10cm)', '> 60inches(152.40cm) but < 65inches(165.10cm)'), ('> 65inches(165.10cm) but < 70inches(177.80cm)', '> 65inches(165.10cm) but < 70inches(177.80cm)'), ('> 70inches(177.80) but < 75inches(190.50cm)', '> 70inches(177.80) but < 75inches(190.50cm)'), ('> 75inches(190.50cm) but < 80inches(203.20cm)', '> 75inches(190.50cm) but < 80inches(203.20cm)'), ('> 80inches(203.20cm) but < 85inches(215.90cm)', '> 80inches(203.20cm) but < 85inches(215.90cm)'), ('> 85inches(215.90cm) but < 90inches(228.6)', '> 85inches(215.90cm) but < 90inches(228.6cm)'), ('> 90inches(228.6cm)', '> 90inches(228.6cm))')], max_length=100),
        ),
    ]
