# Generated by Django 3.0.2 on 2020-05-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200525_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerynew',
            name='gallery_image',
            field=models.ImageField(default='image.png', upload_to='gallery/'),
        ),
    ]
