# Generated by Django 3.0.2 on 2020-05-26 21:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200525_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerynew',
            name='gallery_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='gallery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_pics'),
        ),
    ]
