# Generated by Django 3.0.2 on 2020-05-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200526_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
